const tickerSettings = {speed:1};
const supporters = [
	// Supersonic Members
	{name:`felax`,tier:1},
	{name:`Gene Leaphart`,tier:1},

	// One-time Supporters
	{name:`Ahrbee Imkerei`,tier:0},
	{name:`Alex Tran`,tier:0},
	{name:`Alexander van Velzen`,tier:0},
	{name:`Alison Neill`,tier:0},
	{name:`Amanda Drage Art`,tier:0},
	{name:`Andrew Dransfield`,tier:0},
	{name:`Angel Morales`,tier:0},
	{name:`Angela Gürber`,tier:0},
	{name:`Angela Rau`,tier:0},
	{name:`Annalise Batista`,tier:0},
	{name:`Ann-Marie Barron`,tier:0},
	{name:`Arinola Fryar`,tier:0},
	{name:`Armen Gevorgyan`,tier:0},
	{name:`Astrology by Lyra`,tier:0},
	{name:`Avishay Bar-El`,tier:0},
	{name:`Beat Scheidegger`,tier:0},
	{name:`Beate Teuber`,tier:0},
	{name:`Beth Flanagan`,tier:0},
	{name:`Big Amateur Telescope Ltd`,tier:0},
	{name:`bob palatka`,tier:0},
	{name:`Bradley Tripp`,tier:0},
	{name:`Brian Beaudry`,tier:0},
	{name:`Bruno Brys`,tier:0},
	{name:`Bryan Stevens`,tier:0},
	{name:`Carob Communications`,tier:0},
	{name:`Charles Brown`,tier:0},
	{name:`Christiana Schweizer`,tier:0},
	{name:`Christoph Pfluger`,tier:0},
	{name:`Ciel`,tier:0},
	{name:`cKoruss`,tier:0},
	{name:`Clyde Carman`,tier:0},
	{name:`Composite Inspection and Consulting, LLC`,tier:0},
	{name:`computers dot mom`,tier:0},
	{name:`Consortium of Universities`,tier:0},
	{name:`Constanze Mülders`,tier:0},
	{name:`Courtney Rush`,tier:0},
	{name:`Crista Bromley`,tier:0},
	{name:`Daiana Arhex`,tier:0},
	{name:`Damir Mrkulic`,tier:0},
	{name:`Daniel Martin`,tier:0},
	{name:`Daniel OConnor`,tier:0},
	{name:`Darius Tulbure`,tier:0},
	{name:`Darren Reeser`,tier:0},
	{name:`David Johnson`,tier:0},
	{name:`David Jones`,tier:0},
	{name:`David Tyler`,tier:0},
	{name:`Debra LeClair`,tier:0},
	{name:`Debrorah Havens`,tier:0},
	{name:`Don Desrosiers`,tier:0},
	{name:`Donald Leroux`,tier:0},
	{name:`Douglas Ignacio Cunha`,tier:0},
	{name:`Dr. Lydia Polwin-Plass`,tier:0},
	{name:`Dramatic Pause`,tier:0},
	{name:`duncan knowles`,tier:0},
	{name:`Elizabeth Bodenham`,tier:0},
	{name:`Ellen Stoecker`,tier:0},
	{name:`Ernst Wicki`,tier:0},
	{name:`Evelyn Alicea-Santiago`,tier:0},
	{name:`EVOLUCE, druzstvo`,tier:0},
	{name:`Frank Carey`,tier:0},
	{name:`Friedrich und Brigitte Gönges GbR`,tier:0},
	{name:`Gary Geissler`,tier:0},
	{name:`GB-Magic`,tier:0},
	{name:`Gerd Altmann`,tier:0},
	{name:`Gill Westwood`,tier:0},
	{name:`Goran Nikolic`,tier:0},
	{name:`Grethe Jønsson`,tier:0},
	{name:`Griffin Studios`,tier:0},
	{name:`Hans Mahn`,tier:0},
	{name:`herwann asseh`,tier:0},
	{name:`Ilse Spruit`,tier:0},
	{name:`Isabelle Ochs`,tier:0},
	{name:`jacob R`,tier:0},
	{name:`James Daugherty`,tier:0},
	{name:`Javier Roca de Togores Ginestar`,tier:0},
	{name:`jens Jörgens`,tier:0},
	{name:`Jeremy Chappell`,tier:0},
	{name:`Jerzy Wojgienica`,tier:0},
	{name:`Joel Tretin Advertising LLC`,tier:0},
	{name:`John Hain`,tier:0},
	{name:`joseph Deer`,tier:0},
	{name:`joshua holton`,tier:0},
	{name:`Julie Randell`,tier:0},
	{name:`Jürgen Wolski`,tier:0},
	{name:`Karine REINER`,tier:0},
	{name:`Karapet Simonyan`,tier:0},
	{name:`Katherine Brasuell`,tier:0},
	{name:`Keith Stevenson`,tier:0},
	{name:`Kenshin Saeteurn`,tier:0},
	{name:`Kerstin Brachaus - Mechow`,tier:0},
	{name:`khalid Al Shanfari`,tier:0},
	{name:`Kim McCalmon`,tier:0},
	{name:`KP Cave`,tier:0},
	{name:`Kurt Schneider`,tier:0},
	{name:`Laura Jedeed`,tier:0},
	{name:`Lauri Pahkala`,tier:0},
	{name:`Linda Nordstrom`,tier:0},
	{name:`Linden C Lestrade`,tier:0},
	{name:`Loretta Reiter`,tier:0},
	{name:`Luis Siquot`,tier:0},
	{name:`Ma Wai Kin`,tier:0},
	{name:`Malcolm Saul`,tier:0},
	{name:`Manuel CORDERO DOMINGUEZ`,tier:0},
	{name:`Marcela Vintimilla`,tier:0},
	{name:`Margarete Fuhrmann`,tier:0},
	{name:`Maria Gielen`,tier:0},
	{name:`Maria Santos`,tier:0},
	{name:`Mark Langner`,tier:0},
	{name:`Markus Menzi`,tier:0},
	{name:`Martin Plank`,tier:0},
	{name:`Mary Ferrara`,tier:0},
	{name:`Melissa Stoltz`,tier:0},
	{name:`Mellisa Ziselo`,tier:0},
	{name:`Michael Kretzschmar`,tier:0},
	{name:`Mikaël WAGNER`,tier:0},
	{name:`Michel Houde`,tier:0},
	{name:`Moreen Reed`,tier:0},
	{name:`Moriah J. Williams`,tier:0},
	{name:`Mr H Engineering`,tier:0},
	{name:`Narik Chase Studios`,tier:0},
	{name:`Nash Smith`,tier:0},
	{name:`Nathalie Bernier`,tier:0},
	{name:`Nemileanu`,tier:0},
	{name:`Nils Skywalker Isberg Erenough`,tier:0},
	{name:`Numbered`,tier:0},
	{name:`Pages Editorial Service`,tier:0},
	{name:`Pattern Research, Inc.`,tier:0},
	{name:`PIERRE perrenoud`,tier:0},
	{name:`Pike-Attack`,tier:0},
	{name:`R.-Andreas Klein`,tier:0},
	{name:`Randy Hall`,tier:0},
	{name:`Ravelle Suban London`,tier:0},
	{name:`Richard Murray`,tier:0},
	{name:`Robert Grammer`,tier:0},
	{name:`Robert Sparks`,tier:0},
	{name:`robertodallavecchia`,tier:0},
	{name:`Roberto Grassilli`,tier:0},
	{name:`Roland Sharman`,tier:0},
	{name:`Ronel Dupuy`,tier:0},
	{name:`ryan louth`,tier:0},
	{name:`Sabine Schonfeldt`,tier:0},
	{name:`Sarah Carroll`,tier:0},
	{name:`Sascha Gross`,tier:0},
	{name:`Scherelene Schatz`,tier:0},
	{name:`Scott Kennedy`,tier:0},
	{name:`Shawn Gentert`,tier:0},
	{name:`Sherry Peel Jackson`,tier:0},
	{name:`Sibylle Grosjean`,tier:0},
	{name:`Simone Oggianu`,tier:0},
	{name:`skywalker Erenough`,tier:0},
	{name:`Stanton Barrett Motorsports`,tier:0},
	{name:`StellaDanza`,tier:0},
	{name:`Steven Hardy`,tier:0},
	{name:`Stoller System, LLC`,tier:0},
	{name:`Susan Morley`,tier:0},
	{name:`Susan Nass`,tier:0},
	{name:`Sylvia Fuhrma`,tier:0},
	{name:`Syna Werkmeister`,tier:0},
	{name:`TAI BAN`,tier:0},
	{name:`Tanglewood West dba Abiquiu News`,tier:0},
	{name:`Taylor O'Dair`,tier:0},
	{name:`Teresa Hutton`,tier:0},
	{name:`Terry Hueffed`,tier:0},
	{name:`Terry Safko`,tier:0},
	{name:`TETNTM`,tier:0},
	{name:`Thomas Avender-Fuchs`,tier:0},
	{name:`Thomas Dietz`,tier:0},
	{name:`Thomas Przestwor`,tier:0},
	{name:`Thomas Vetter-Wolf`,tier:0},
	{name:`Tim Oliver Georg`,tier:0},
	{name:`Together Press`,tier:0},
	{name:`Tom Marcoux Media, LLC`,tier:0},
	{name:`Tomasz Batorowicz`,tier:0},
	{name:`Trees for a Change LLC`,tier:0},
	{name:`TRex Enterprises`,tier:0},
	{name:`Valkyrie Enterprises`,tier:0},
	{name:`Victoria Carlie`,tier:0},
	{name:`Viktor Karlsson`,tier:0},
	{name:`White Criss Wilson`,tier:0},
	{name:`Willy Chen`,tier:0},
	{name:`Yaron Toor`,tier:0},
	{name:`Yuming Chen`,tier:0},
	{name:`Zee Colin`,tier:0},
]
const randomSupporters = getRandomSupporters([...supporters]);
function getRandomSupporters(s) {
	for (let i = s.length - 1; i > 0; i--) {const j = Math.floor(Math.random() * (i + 1)); [s[i], s[j]] = [s[j], s[i]]};
	return s;
}
