const worldEvents = [
	{
		date:"1903-12-17",
		title:"<p>The </p><b>first powered airplane</b><p> takes off.</p>",
		description:"The first successful airplane (the Wright Flyer) takes off from Devil Hills, North Carolina, piloted by Orville Wright.",
		major:true,
		type:"invention",
	},
	{
		date:"1908-10-1",
		title:"<p>The </p><b>first production Model T</b><p> is built.</p>",
		description:"The Model T was the first mass produced car selling 15 million by 1927.",
		major:true,
		type:"invention",
	},
	{
		date:"1912-4-10",
		title:"<b>The Titanic sets sail</b><p>, bound for New York City.</p>",
		description:"The Titanic, which was the largest passenger ship at the time, departed from Southampton, England.",
		major:true,
		type:"project-finishes",
	},
	{
		date:"1912-4-14",
		title:"<b>The Titanic sinks</b><p> after striking an iceberg in the North Atlantic Ocean.</p>",
		description:"The Titanic struck an iceberg at around 11:40 PM on the 14th and eventually sank below the surface at around 2:20 AM on the 15th taking with it the lives of around 1,500 people.",
		major:true,
		type:"incident",
	},
	{
		date:"1914-1-1",
		title:"<p>The </p><b>first scheduled airline flight</b><p> takes off.</p>",
		description:"The first ever airline flight (the St. Petersburg-Tampa Airboat Line) takes off across Tampa Bay. The flight lasted only around 23 minutes; 11 hours less than by rail.",
		major:true,
		type:"human-accomplishment",
	},
	{
		date:"1914-7-28",
		title:"<b>World War I</b><p> begins after Austria-Hungary declares war on Serbia.</p>",
		description:"The assassination of Austrian Archduke Franz Ferdinand (heir to the Austro-Hungarian Empire) on June 28, 1914 was the initial spark which started World War I.",
		major:true,
		type:"war-begins",
	},
	{
		date:"1915-3-3",
		title:"<b>NACA is founded</b><p>.</p>",
		description:"NACA, now NASA, is founded.",
		type:"company-founded",
	},
	{
		date:"1918-2",
		title:"<p>An outbreak of the </p><b>Spanish Flu</b><p> begins.</p>",
		description:"Starting in February, 1918, and lasting around 2 years, this outbreak is estimated to have infected 40% of the world's population at the time, killing around 50 million people making it one of, if not the worse pandemic in history.",
		major:true,
		type:"pandemic-begins",
	},
	{
		date:"1918-11-18",
		title:"<b>World War I</b><p> ends.</p>",
		description:"An armistice (essentially a truce) was signed between the Germans and the Allies, ending World War I.",
		major:true,
		type:"war-ends",
		deaths:40000000,
	},
	{
		date:"1919-1-15",
		title:"<b>The Great Molasses Flood</b><p> occurs.</p>",
		description:"A disaster that occurred in Boston's North End, when a molasses tank ruptured and released over 2 million gallons of molasses.",
		type:"incident",
	},
	{
		date:"1927",
		title:"<p>The </p><b>world population surpasses 2 billion</b><p>.</p>",
		description:"",
		type:"world-population-increases",
	},
	{
		date:"1927-8",
		title:"<b>The Great Depression</b><p> starts in the United States.</p>",
		description:"The Great Depression was a severe global economic downturn which led to high rates of unemployment and poverty.",
		major:true,
		type:"crisis-begins",
	},
	{
		date:"1939",
		title:"<b>The Great Depression</b><p> ends.</p>",
		description:"The Great Depression was a severe global economic downturn which led to high rates of unemployment and poverty.",
		type:"crisis-ends",
	},
	{
		date:"1939-9-1",
		title:"<b>World War II</b><p> begins when Germany invades Poland.</p>",
		description:"After Germany invaded Poland, Great Britain and France declared war on Germany, beginning World War II.",
		major:true,
		type:"war-begins",
	},
	{
		date:"1939-9-13",
		title:"<p>The </p><b>first helicopter</b><p> flight.</p>",
		description:"The first successful helicopter (VS-300) takes off in Stratford, Connecticut, piloted by Igor Sikorsky. The flight was tethered and only lasted a few seconds, but it was a successful proof of concept.",
		major:true,
		type:"invention",
	},
	{
		date:"1945-5-8",
		title:"<b>World War II</b><p> in Europe ends after Germany surrenders.</p>",
		description:"After nearly 6 years of war, Germany surrenders, ending World War II in Europe.",
		type:"war-partially-ends",
	},
	{
		date:"1945-8-6",
		title:"<p>An </p><b>atomic bomb</b><p> is dropped on </p><b>Hiroshima</b><p>, Japan.</p>",
		description:"The first ever atomic bomb used in war, Little Boy, is dropped on Hiroshima, Japan, killing 140,000 people.",
		major:true,
		type:"human-destruction",
	},
	{
		date:"1945-8-9",
		title:"<p>An </p><b>atomic bomb</b><p> is dropped on </p><b>Nagasaki</b><p>, Japan.</p>",
		description:"The second ever atomic bomb used in war, Fat Man, is dropped on Nagasaki, Japan, killing 74,000 people.",
		major:true,
		type:"human-destruction",
	},
	{
		date:"1945-9-2",
		title:"<b>World War II</b><p> ends after Japan surrenders.</p>",
		description:"Shortly after the surrender of Germany, Japan surrenders to the US, ending World War II.",
		major:true,
		type:"war-ends",
		deaths:60000000,
	},
	{
		date:"1945-12-10",
		title:"<p>The </p><b>first computer</b><p> is put to work.</p>",
		description:"The ENIAC (Electronic Numerical Integrator and Computer) was invented sometime in 1945 and was first put to work on December 10, 1945.",
		major:true,
		type:"invention",
	},
	{
		date:"1947-3-12",
		title:"<p>The </p><b>Cold War</b><p> begins.</p>",
		description:"The Cold War was a geopolitical rivalry between the United States and the Soviet Union, characterized by ideological clashes between capitalism and communism. Though no direct war occurred, it fueled arms races, proxy wars, and political tensions worldwide.",
		major:true,
		type:"war-begins",
	},
	{
		date:"1955-11-1",
		title:"<p>The </p><b>Vietnam War</b><p> begins.</p>",
		description:"The Vietnam War was an armed conflict in Vietnam, Laos, and Cambodia fought between North Vietnam and South Vietnam and their allies.",
		major:true,
		type:"war-begins",
	},
	{
		date:"1958-7-27",
		title:"<b>NASA is founded</b><p>.</p>",
		description:"NASA, previously NACA, is founded.",
		type:"company-founded",
	},
	{
		date:"1960-5-22",
		title:"<p>The </p><b>Valdivia earthquake</b><p> occurs of magnitude 9.2.</p>",
		description:"The Valdivia earthquake (also known as the Chilean earthquake) was a magnitude 9.2 earthquake and is the most powerful earthquake ever recorded as of 2025.",
		major:true,
		type:"earthquake",
	},
	{
		date:"1960-7",
		title:"<p>The </p><b>world population surpasses 3 billion</b><p>.</p>",
		description:"",
		type:"world-population-increases",
	},
	{
		date:"1963-11-22",
		title:"<b>John F. Kennedy is assassinated</b><p>.</p>",
		description:"The 35th president of the United States was assassinated while riding in his motorcade in Dallas, Texas. The assassin is highly debated to this day.",
		major:true,
		type:"human-destruction",
	},
	{
		date:"1964-12-22",
		title:"<p>The </p><b>SR-71 Blackbird makes its first flight</b><p>.</p>",
		description:"The first SR-71 Blackbird takes flight from Palmdale, California.",
		major:true,
		type:"human-accomplishment",
	},
	{
		date:"1968-9",
		title:"<p>The </p><b>first electric printer</b><p> is released.</p>",
		description:"The Epson EP-101 is released.",
		major:true,
		type:"invention",
	},
	{
		date:"1969-7-20",
		title:"<b>Humans land on the Moon</b><p> for the first time.</p>",
		description:"During the Apollo 11 mission, Neil Armstrong becomes the first human to set foot on the Moon.",
		major:true,
		type:"human-accomplishment",
	},
	{
		date:"1972-12-14",
		title:"<b>The last time humans are on the Moon</b><p>.</p>",
		description:"Apollo 17 was the last mission to the Moon.",
		type:"last-event",
	},
	{
		date:"1973-4-3",
		title:"<p>The </p><b>first mobile phone</b><p> is showcased.</p>",
		description:"The first handheld mobile phone is demonstrated in New York City by Martin Cooper.",
		major:true,
		type:"invention",
	},
	{
		date:"1974-4",
		title:"<p>The </p><b>world population surpasses 4 billion</b><p>.</p>",
		description:"",
		type:"world-population-increases",
	},
	{
		date:"1975-4-4",
		title:"<b>Microsoft is founded</b><p>.</p>",
		description:"Bill Gates and Paul Allen officially founded Microsoft in Albuquerque, New Mexico.",
		type:"company-founded",
	},
	{
		date:"1975-4-30",
		title:"<p>The </p><b>Vietnam War</b><p> ends.</p>",
		description:"The Vietnam War was an armed conflict in Vietnam, Laos, and Cambodia fought between North Vietnam and South Vietnam and their allies.",
		type:"war-ends",
		deaths:4400000,
	},
	{
		date:"1975",
		title:"<p>The </p><b>first digital camera</b><p> is invented.</p>",
		description:"It was created by Kodak engineer Steve Sasson and weighed 4.5 kg (10 lbs).",
		major:true,
		type:"invention",
	},
	{
		date:"1976-1-21",
		title:"<b>Concorde makes its first commercial flights</b><p>.</p>",
		description:"The first Concordes with commercial passengers simultaneously take flight. The London flight was headed to Bahrain in the Persian Gulf, and the Paris to Rio de Janeiro via Senegal in West Africa.",
		major:true,
		type:"human-accomplishment",
	},
	{
		date:"1976-4-1",
		title:"<b>Apple is founded</b><p>.</p>",
		description:"Steve Jobs and Steve Wozniak officially founded Apple Computer, Inc.",
		type:"company-founded",
	},
	{
		date:"1980-5-18",
		title:"<b>Mt. Saint Helens erupts</b><p>.</p>",
		description:"The eruption of Mt. Saint Helens was the most deadly volcanic event in the history of the United States (as of 2025) killing around 57 people.",
		major:true,
		type:"volcanic-eruption",
	},
	{
		date:"1981-4",
		title:"<p>The </p><b>first laptop is released</b><p>.</p>",
		description:"The Osbourne 1, named after the inventor, Adam Osbourne, is considered the first laptop to be made and sold.",
		major:true,
		type:"invention",
	},
	{
		date:"1981",
		title:"<b>3D printing is invented</b><p>.</p>",
		description:"Dr. Hideo Kodama of Japan patented a rapid prototyping system that used a photosensitive resin to create objects layer by layer.",
		major:true,
		type:"invention",
	},
	{
		date:"1983-1-1",
		title:"<b>Internet is invented</b><p>.</p>",
		description:"Though initially designed for sharing of information between universities and institutes, the World Wide Web (WWW) has become a public, ordinary thing of today.",
		major:true,
		type:"invention",
	},
	{
		date:"1983-6-5",
		title:"<p>The </p><b>Second Sudanese Civil War</b><p> begins.</p>",
		description:"A conflict between the central Sudanese government and the Sudan People's Liberation Army.",
		major:true,
		type:"war-begins",
	},
	{
		date:"1983-7-23",
		title:"<p>The </p><b>Sri Lankan Civil War</b><p> begins.</p>",
		description:"An intermittent insurgency against the government by the Liberation Tigers of Tamil Eelam (LTTE, also known as the Tamil Tigers) led by Velupillai Prabhakaran.",
		major:true,
		type:"war-begins",
	},
	{
		date:"1985-9-1",
		title:"<p>The </p><b>Titanic wreck is found</b><p> 73 years after it sank.</p>",
		description:"An American-French expedition led by Dr. Robert Ballard and Jean-Luis Michel eventually spotted on of the boilers which led them to the rest of the wreckage.",
		major:true,
		type:"wreck-discovery",
	},
	{
		date:"1985-11-20",
		title:"<p>The first version of </p><b>Windows is released</b><p>.</p>",
		description:"The first version of Windows, Windows 1.0, is released as a graphical operating system shell for MS-DOS.",
		type:"product-launched",
	},
	{
		date:"1986-4-26",
		title:"<p>The </p><b>Chernobyl</b><p> nuclear disaster occurs.</p>",
		description:"The explosion of reactor number 4 caused the accident, resulting in around 30 deaths.",
		major:true,
		type:"incident",
	},
	{
		date:"1987-7-11",
		title:"<p>The </p><b>world population surpasses 5 billion</b><p>.</p>",
		description:"",
		type:"world-population-increases",
	},
	{
		date:"1990-4-24",
		title:"<p>The </p><b>Hubble Space Telescope</b><p> is launched.</p>",
		description:"Hubble led to many discoveries in space.",
		major:true,
		type:"spacecraft-launch",
	},
	{
		date:"1991-12-26",
		title:"<p>The </p><b>Cold War</b><p> ends.</p>",
		description:"The Cold War was a geopolitical rivalry between the United States and the Soviet Union, characterized by ideological clashes between capitalism and communism. Though no direct war occurred, it fueled arms races, proxy wars, and political tensions worldwide.",
		type:"war-ends",
	},
	{
		date:"1992-1-11",
		title:"<p>The </p><b>Algerian Civil War</b><p> begins.</p>",
		description:"The Algerian Civil War, known in Algeria as the Black Decade, was a civil war fought between the Algerian government and various Islamist rebel groups.",
		major:true,
		type:"war-begins",
	},
	{
		date:"1993-2-10",
		title:"<b>GPS</b><p> becomes fully operational with 24 satellites.</p>",
		description:"Though it was initially invented in 1973, GPS became fully operational in February, 1993 and was made available to civilians on December 8, 1993.",
		major:true,
		type:"product-launched",
	},
	{
		date:"1996-2-13",
		title:"<p>The </p><b>Nepalese Civil War</b><p> begins.</p>",
		description:"A protracted armed conflict that took place in the then Kingdom of Nepal. It saw countrywide fighting between the Kingdom rulers and the Communist Party of Nepal (Maoist).",
		type:"war-begins",
	},
	{
		date:"1996-9",
		title:"<p>The first </p><b>White LED</b><p> by Nichia is released.</p>",
		description:"The revolution of LED lighting would not have been possible without white LEDs.",
		major:true,
		type:"product-launched",
	},
	{
		date:"1997-10-15",
		title:"<p>The </p><b>fastest land speed record</b><p> is set.</p>",
		description:"Andy Green, a Royal Air Force pilot, sets the world land speed record in the ThrustSSC.",
		type:"record-set",
	},
	{
		date:"1998-8-2",
		title:"<p>The </p><b>Second Congo War</b><p> begins.</p>",
		description:"The war initially erupted when Congolese president Laurent-Désiré Kabila turned against his former allies from Rwanda and Uganda, who had helped him seize power. Eventually, the conflict expanded, drawing in nine African nations and approximately 25 armed groups, making it one of the largest wars in African history.",
		major:true,
		type:"war-begins",
	},
	{
		date:"1998-9-4",
		title:"<b>Google is founded</b><p>.</p>",
		description:"Page and Brin officially founded Google Inc. in a garage in Menlo Park, California.",
		type:"company-founded",
	},
	{
		date:"1999-4-21",
		title:"<p>The </p><b>Second Liberian Civil War</b><p> begins.</p>",
		description:"A civil war in the West African nation of Liberia.",
		type:"war-begins",
	},
	{
		date:"1999-8-7",
		title:"<p>The </p><b>Second Chechen War</b><p> begins.</p>",
		description:"The war took place in Chechnya and the border regions of the North Caucasus between the Russian Federation and the breakaway Chechen Republic of Ichkeria.",
		type:"war-begins",
	},
	{
		date:"1999-10-9",
		title:"<p>The </p><b>SR-71 Blackbird makes its last flight</b><p>.</p>",
		description:"The SR-71 Blackbird made its final flight at Edwards Air Force Base.",
		type:"last-event",
	},
	{
		date:"1999-10-12",
		title:"<p>The </p><b>world population surpasses 6 billion</b><p>.</p>",
		description:"",
		type:"world-population-increases",
	},
	{
		date:"2001-1-15",
		title:"<b>Wikipedia is founded</b><p>.</p>",
		description:"Now one of the most used websites in the world, Wikipedia was founded by Jimmy Wales and Larry Sanger.",
		type:"company-founded",
	},
	{
		date:"2001",
		title:"<b>4K screens are created</b><p>.</p>",
		description:"The IBM T220/T221 LCD monitors were the first 4K screens",
		type:"invention",
	},
	{
		date:"2001-9-11",
		title:"<p>The </p><b>September 11 attacks</b><p> (commonly known as 9/11).</p>",
		description:"The events of 9/11 (the collapse of the World Trade Center's Twin Towers in New York City, the event at the Pentagon, etc.) caused a major shift in worldwide security and restrictions, especially in commercial flight.",
		major:true,
		type:"incident",
	},
	{
		date:"2001-10-7",
		title:"<p>The </p><b>War in Afghanistan</b><p> begins.</p>",
		description:"An armed conflict launched as a direct response to the September 11 attacks. The war began when an international military coalition led by the United States invaded Afghanistan, declaring Operation Enduring Freedom as part of the earlier-declared war on terror.",
		major:true,
		type:"war-begins",
	},
	{
		date:"2002-1-1",
		title:"<b>The Euro enters circulation</b><p>.</p>",
		description:"Coins and banknotes for the Euro are launched, causing the biggest cash changeover in history for 12 EU countries.",
		major:true,
		type:"product-launched",
	},
	{
		date:"2002-2-8",
		title:"<p>The </p><b>Algerian Civil War</b><p> ends.</p>",
		description:"The Algerian Civil War, known in Algeria as the Black Decade, was a civil war fought between the Algerian government and various Islamist rebel groups.",
		type:"war-begins",
	},
	{
		date:"2002-3-14",
		title:"<b>SpaceX is founded</b><p>.</p>",
		description:"SpaceX is founded by Elon Musk.",
		type:"company-founded",
	},
	{
		date:"2002-9-19",
		title:"<p>The </p><b>First Ivorian Civil War</b><p> begins.</p>",
		description:"The First Ivorian Civil War was a civil conflict in the Ivory Coast (Côte d'Ivoire) that began with a military rebellion.",
		type:"war-begins",
	},
	{
		date:"2002-10-13",
		title:"<b>Blender</b><p> is first released as open-source.</p>",
		description:"The 3D application, Blender, is released to the public as open-source (though it existed before this as a free but paid upgradable program).",
		type:"product-launched",
	},
	{
		date:"2003-2-26",
		title:"<p>The </p><b>War in Darfur</b><p> begins.</p>",
		description:"A major armed conflict in the Darfur region of Sudan that began when the Sudan Liberation Movement (SLM) and the Justice and Equality Movement (JEM) rebel groups began fighting against the government of Sudan, which they accused of oppressing Darfur's non-Arab population.",
		major:true,
		type:"war-begins",
	},
	{
		date:"2003-3-20",
		title:"<p>The </p><b>Iraq War</b><p> begins.</p>",
		description:"Beginning with the invasion of the United States into Iraq and the overthrow of the Ba'athist government, the war resulted in the death of hundreds of thousands of people.",
		major:true,
		type:"war-begins",
	},
	{
		date:"2003-7-18",
		title:"<p>The </p><b>Second Congo War</b><p> ends.</p>",
		description:"The war initially erupted when Congolese president Laurent-Désiré Kabila turned against his former allies from Rwanda and Uganda, who had helped him seize power. Eventually, the conflict expanded, drawing in nine African nations and approximately 25 armed groups, making it one of the largest wars in African history.",
		type:"war-ends",
		deaths:5400000,
	},
	{
		date:"2003",
		title:"<b>4K video cameras are made</b><p>.</p>",
		description:"The Dalsa Origin was the first 4K video camera, used for cinematographic purposes",
		major:true,
		type:"invention",
	},
	{
		date:"2003-8-18",
		title:"<p>The </p><b>Second Liberian Civil War</b><p> ends.</p>",
		description:"A civil war in the West African nation of Liberia.",
		type:"war-ends",
		deaths:50000,
	},
	{
		date:"2003-11-26",
		title:"<b>Concorde makes its last flight</b><p>.</p>",
		description:"The Concorde (fastest commercial airline ever and the only supersonic airline) makes its last flight from Heathrow Airport to Bristol, England.",
		type:"last-event",
	},
	{
		date:"2004-2-4",
		title:"<b>Facebook is launched</b><p>.</p>",
		description:"Launched by Mark Zuckerberg, it was originally under the name of \"TheFacebook\" and located at thefacebook.com.",
		type:"social-media-launch",
	},
	{
		date:"2004-3-16",
		title:"<p>The </p><b>War in North-West Pakistan</b><p> begins.</p>",
		description:"An armed conflict involving Pakistan and Islamist militant groups.",
		type:"war-begins",
	},
	{
		date:"2005-1-9",
		title:"<p>The </p><b>Second Sudanese Civil War</b><p> ends.</p>",
		description:"A conflict between the central Sudanese government and the Sudan People's Liberation Army.",
		type:"war-ends",
		deaths:1500000,
	},
	{
		date:"2005-2-4",
		title:"<b>YouTube is launched</b><p>.</p>",
		description:"Steve Chen, Chad Hurley, and Jawed Karim launched YouTube.",
		type:"social-media-launch",
	},
	{
		date:"2005-6-23",
		title:"<b>Reddit is launched</b><p>.</p>",
		description:"Launched by Steve Huffman, Alexis Ohanian, and Aaron Swartz in Medford, Massachusetts.",
		type:"social-media-launch",
	},
	{
		date:"2006-3-21",
		title:"<b>Twitter is launched</b><p>.</p>",
		description:"Now known as X, Twitter was launched by Jack Dorsey, Evan Williams, and Biz Stone.",
		type:"social-media-launch",
	},
	{
		date:"2006-6-17",
		title:"<p>The </p><b>Somalia War</b><p> begins.</p>",
		description:"Beginning when military forces from Ethiopia, supported by the United States, invaded Somalia to depose the Islamic Courts Union (ICU) and install the Transitional Federal Government (TFG). The conflict continued after the invasion when an anti-Ethiopian insurgency emerged and rapidly escalated. During 2007 and 2008, the insurgency recaptured the majority of territory lost by the ICU.",
		type:"war-begins",
	},
	{
		date:"2006-7-12",
		title:"<p>The </p><b>2006 Lebanon War</b><p> begins.</p>",
		description:"An armed conflict in Lebanon, fought between Hezbollah and Israel.",
		type:"war-begins",
	},
	{
		date:"2006-8-14",
		title:"<p>The </p><b>2006 Lebanon War</b><p> ends.</p>",
		description:"An armed conflict in Lebanon, fought between Hezbollah and Israel.",
		type:"war-ends",
		deaths:1700,
	},
	{
		date:"2006-11-21",
		title:"<p>The </p><b>Nepalese Civil War</b><p> ends.</p>",
		description:"A protracted armed conflict that took place in the then Kingdom of Nepal. It saw countrywide fighting between the Kingdom rulers and the Communist Party of Nepal (Maoist).",
		type:"war-ends",
		deaths:19100,
	},
	{
		date:"2006-12-11",
		title:"<p>The </p><b>Mexican Drug War</b><p> begins.</p>",
		description:"An asymmetric armed conflict between the Mexican government and various drug trafficking syndicates.",
		major:true,
		type:"war-begins",
	},
	{
		date:"2007-3-4",
		title:"<p>The </p><b>First Ivorian Civil War</b><p> ends.</p>",
		description:"The First Ivorian Civil War was a civil conflict in the Ivory Coast (Côte d'Ivoire) that began with a military rebellion.",
		type:"war-ends",
		deaths:3400,
	},
	{
		date:"2007-6-29",
		title:"<p>The </p><b>first iPhone</b><p> is released.</p>",
		description:"The iPhone 1 is what largely started the huge rise in smartphones.",
		major:true,
		type:"product-launched",
	},
	{
		date:"2008-2",
		title:"<p>The first </p><b>Tesla Roadster</b><p> is delivered.</p>",
		description:"This sparked a huge innovation into electric cars.",
		major:true,
		type:"product-launched",
	},
	{
		date:"2008-8-1",
		title:"<p>The </p><b>Russo-Georgian War</b><p> begins.</p>",
		description:"A war waged against Georgia by the Russian Federation and the Russian-backed separatist regions of South Ossetia and Abkhazia. The fighting took place in the strategically important South Caucasus region. It is regarded as the first European war of the 21st century.",
		type:"war-begins",
	},
	{
		date:"2008-8-16",
		title:"<p>The </p><b>Russo-Georgian War</b><p> ends.</p>",
		description:"A war waged against Georgia by the Russian Federation and the Russian-backed separatist regions of South Ossetia and Abkhazia. The fighting took place in the strategically important South Caucasus region. It is regarded as the first European war of the 21st century.",
		type:"war-ends",
		deaths:365,
	},
	{
		date:"2008-8-18",
		title:"<b>Bitcoin is launched</b><p>.</p>",
		description:"One of the first and most expensive cryptocurrencies to date.",
		type:"product-launched",
	},
	{
		date:"2008-12-27",
		title:"<p>The </p><b>Gaza War</b><p> begins.</p>",
		description:"An armed conflict between Gaza Strip Palestinian paramilitary groups and the Israel Defense Forces (IDF).",
		type:"war-begins",
	},
	{
		date:"2009-1-18",
		title:"<p>The </p><b>Gaza War</b><p> ends.</p>",
		description:"An armed conflict between Gaza Strip Palestinian paramilitary groups and the Israel Defense Forces (IDF).",
		type:"war-ends",
		deaths:1400,
	},
	{
		date:"2009-1-30",
		title:"<p>The </p><b>Somalia War</b><p> ends.</p>",
		description:"Beginning when military forces from Ethiopia, supported by the United States, invaded Somalia to depose the Islamic Courts Union (ICU) and install the Transitional Federal Government (TFG). The conflict continued after the invasion when an anti-Ethiopian insurgency emerged and rapidly escalated. During 2007 and 2008, the insurgency recaptured the majority of territory lost by the ICU.",
		type:"war-ends",
		deaths:18000,
	},
	{
		date:"2009-4-16",
		title:"<p>The </p><b>Second Chechen War</b><p> ends.</p>",
		description:"The war took place in Chechnya and the border regions of the North Caucasus between the Russian Federation and the breakaway Chechen Republic of Ichkeria.",
		type:"war-ends",
		deaths:65000,
	},
	{
		date:"2009-5-13",
		title:"<p>The </p><b>Sri Lankan Civil War</b><p> ends.</p>",
		description:"An intermittent insurgency against the government by the Liberation Tigers of Tamil Eelam (LTTE, also known as the Tamil Tigers) led by Velupillai Prabhakaran.",
		type:"war-ends",
		deaths:773000,
	},
	{
		date:"2010-1-4",
		title:"<p>The </p><b>Burj Khalifa</b><p> opens to the public.</p>",
		description:"After nearly 6 years of construction, the Burj Khalifa in Dubai, being the tallest building as of 2025, opens to the public.",
		type:"project-finishes",
	},
	{
		date:"2010-9",
		title:"<p>The </p><b>Prusa Mendel</b><p> 3D Printer is released.</p>",
		description:"This printer is considered the \"Ford Model T\" of 3D printers opening up the 3D printing hobby to a huge crowd.",
		major:true,
		type:"product-launched",
	},
	{
		date:"2010-10-6",
		title:"<b>Instagram is founded</b><p>.</p>",
		description:"Kevin Systrom and Mike Krieger founded Instagram on October 6, 2010.",
		type:"social-media-launch",
	},
	{
		date:"2010-11-28",
		title:"<p>The </p><b>Second Ivorian Civil War</b><p> begins.</p>",
		description:"A military conflict between forces loyal to Laurent Gbagbo, the President of Ivory Coast since 2000, and supporters of the internationally recognized president-elect Alassane Ouattara.",
		type:"war-begins",
	},
	{
		date:"2011-3-11",
		title:"<p>The </p><b>Fukushima</b><p> nuclear disaster occurs.</p>",
		description:"Caused by the 2011 Tōhoku earthquake and tsunami, which resulted in electrical grid failure and damaged nearly all of the power plant's backup energy sources. Considered the worse nuclear disaster since Chernobyl.",
		major:true,
		type:"incident",
	},
	{
		date:"2011-3-11",
		title:"<p>The </p><b>Syrian Civil War</b><p> begins.</p>",
		description:"A multi-sided conflict in Syria involving various state-sponsored and non-state actors.",
		major:true,
		type:"war-begins",
	},
	{
		date:"2011-4-11",
		title:"<p>The </p><b>Second Ivorian Civil War</b><p> ends.</p>",
		description:"A military conflict between forces loyal to Laurent Gbagbo, the President of Ivory Coast since 2000, and supporters of the internationally recognized president-elect Alassane Ouattara.",
		type:"war-ends",
		deaths:3000,
	},
	{
		date:"2011-9-16",
		title:"<b>SnapChat is launched</b><p>.</p>",
		description:"Evan Spiegel and Bobby Murphy relaunch the photo sharing app Picaboo as Snapchat.",
		type:"social-media-launch",
	},
	{
		date:"2011-10-31",
		title:"<p>The </p><b>world population surpasses 7 billion</b><p>.</p>",
		description:"",
		type:"world-population-increases",
	},
	{
		date:"2011-12-18",
		title:"<p>The </p><b>Iraq War</b><p> ends.</p>",
		description:"The US Government officially withdraws its presence in Iraq.",
		type:"war-ends",
		deaths:460000,
	},
	{
		date:"2013-1-7",
		title:"<p>The first </p><b>DJI Phantom</b><p> drone is released.</p>",
		description:"The DJI Phantom (now the Phantom 1) was the first affordable drone which could easily be used by consumers for videography and photography. This release is likely what started the huge drone boom",
		major:true,
		type:"product-launched",
	},
	{
		date:"2014-2-20",
		title:"<p>The </p><b>Russo-Ukrainian War</b><p> begins.</p>",
		description:"The Russo-Ukrainian War (more commonly known simply as the Ukraine War) began after Russia's annexation of Crimea.",
		major:true,
		type:"war-begins",
	},
	{
		date:"2014-5-16",
		title:"<p>The second </p><b>Libyan Civil War</b><p> begins.</p>",
		description:"A multilateral civil war which was fought in Libya among a number of armed groups, but mainly the House of Representatives (HoR) and the Government of National Accord (GNA).",
		type:"war-begins",
	},
	{
		date:"2014-7-8",
		title:"<p>The </p><b>2014 Gaza War</b><p> begins.</p>",
		description:"A military operation launched by Israel in the Gaza Strip, a Palestinian territory.",
		type:"war-begins",
	},
	{
		date:"2014-8-26",
		title:"<p>The </p><b>2014 Gaza War</b><p> ends.</p>",
		description:"A military operation launched by Israel in the Gaza Strip, a Palestinian territory.",
		type:"war-ends",
		deaths:2200,
	},
	{
		date:"2014-9-16",
		title:"<p>The </p><b>Yemeni Civil War</b><p> begins.</p>",
		description:"A multilateral civil war mainly between the Rashad al-Alimi-led Presidential Leadership Council and the Mahdi al-Mashat-led Supreme Political Council, along with their supporters and allies.",
		major:true,
		type:"war-begins",
	},
	{
		date:"2016-9-20",
		title:"<b>TikTok is launched</b><p>.</p>",
		description:"TikTok (also known as Douyin) is launched by ByteDance (a Chinese internet company).",
		type:"social-media-launch",
	},
	{
		date:"2018-6",
		title:"<p>OpenAI's </p><b>first GPT model</b><p> is released.</p>",
		description:"The following years see a huge surge in AI tools and content.",
		major:true,
		type:"product-launched",
	},
	{
		date:"2020-3-11",
		title:"<p>A </p><b>COVID-19 pandemic</b><p> is declared by the World Health Organization.</p>",
		description:"The World Health Organization (WHO) declares the outbreak of COVID-19 a global pandemic. The following months and years see a major rise in global restrictions as well as major changes in the work force and overall society. The origin and cause of the pandemic is one of the most controversial in history.",
		major:true,
		type:"pandemic-begins",
	},
	{
		date:"2020-8-31",
		title:"<p>The </p><b>War in Darfur</b><p> ends.</p>",
		description:"A major armed conflict in the Darfur region of Sudan that began when the Sudan Liberation Movement (SLM) and the Justice and Equality Movement (JEM) rebel groups began fighting against the government of Sudan, which they accused of oppressing Darfur's non-Arab population.",
		type:"war-ends",
		deaths:300000,
	},
	{
		date:"2020-9-27",
		title:"<p>The </p><b>Second Nagorno-Karabakh War</b><p> begins.</p>",
		description:"An armed conflict that took place in the disputed region of Nagorno-Karabakh and the surrounding occupied territories. It was a major escalation of an unresolved conflict over the region, involving Azerbaijan, Armenia and the self-declared Armenian breakaway state of Artsakh.",
		type:"war-begins",
	},
	{
		date:"2020-10-23",
		title:"<p>The second </p><b>Libyan Civil War</b><p> ends.</p>",
		description:"A multilateral civil war which was fought in Libya among a number of armed groups, but mainly the House of Representatives (HoR) and the Government of National Accord (GNA).",
		type:"war-ends",
		deaths:14900,
	},
	{
		date:"2020-11-3",
		title:"<p>The </p><b>Tigray War</b><p> begins.</p>",
		description:"A civil war (that was primarily fought in the Tigray Region of Ethiopia) between forces allied to the Ethiopian federal government and Eritrea on one side, and the Tigray People's Liberation Front (TPLF) on the other.",
		major:true,
		type:"war-begins",
	},
	{
		date:"2020-11-10",
		title:"<p>The </p><b>Second Nagorno-Karabakh War</b><p> ends.</p>",
		description:"An armed conflict that took place in the disputed region of Nagorno-Karabakh and the surrounding occupied territories. It was a major escalation of an unresolved conflict over the region, involving Azerbaijan, Armenia and the self-declared Armenian breakaway state of Artsakh.",
		type:"war-ends",
		deaths:6924,
	},
	{
		date:"2021-5-5",
		title:"<p>The </p><b>Myanmar Civil War</b><p> begins.</p>",
		description:"The war began following Myanmar's long-running insurgencies, which escalated significantly in response to the 2021 military coup d'état and the subsequent violent crackdown on anti-coup protests.",
		type:"war-begins",
	},
	{
		date:"2021-8-30",
		title:"<p>The </p><b>War in Afghanistan</b><p> ends.</p>",
		description:"An armed conflict launched as a direct response to the September 11 attacks. The war began when an international military coalition led by the United States invaded Afghanistan, declaring Operation Enduring Freedom as part of the earlier-declared war on terror.",
		type:"war-ends",
		deaths:200000,
	},
	{
		date:"2021-12-25",
		title:"<p>The </p><b>James Webb Space Telescope</b><p> is launched.</p>",
		description:"As the largest telescope in space, the JWST is equipped with high-resolution and high-sensitivity instruments, allowing it to view objects too old, distant, or faint for the Hubble Space Telescope.",
		major:true,
		type:"spacecraft-launch",
	},
	{
		date:"2022-11-3",
		title:"<p>The </p><b>Tigray War</b><p> ends.</p>",
		description:"A civil war (that was primarily fought in the Tigray Region of Ethiopia) between forces allied to the Ethiopian federal government and Eritrea on one side, and the Tigray People's Liberation Front (TPLF) on the other.",
		type:"war-ends",
		deaths:100000,
	},
	{
		date:"2022-11-15",
		title:"<p>The </p><b>world population surpasses 8 billion</b><p>.</p>",
		description:"",
		type:"world-population-increases",
	},
	{
		date:"2023-4-15",
		title:"<p>The </p><b>Third Sudanese Civil War</b><p> begins.</p>",
		description:"A civil war between two major rival factions of the military government of Sudan, the Sudanese Armed Forces (SAF) under Abdel Fattah al-Burhan and the paramilitary Rapid Support Forces (RSF) and its allies under the Janjaweed leader Hemedti.",
		major:true,
		type:"war-begins",
	},
	{
		date:"2023-5-5",
		title:"<p>The </p><b>COVID-19 pandemic officially ends</b><p>.</p>",
		description:"The World Health Organization (WHO) declares the outbreak of COVID-19 as ended and no longer a public concern.",
		type:"pandemic-ends",
	},
	{
		date:"2023-10-7",
		title:"<p>The </p><b>Israel-Hamas War</b><p> begins.</p>",
		description:"An armed conflict between Israel and Hamas-led Palestinian militant groups.",
		type:"war-begins",
	},
];